### ISSUE TITLE
CI error: ui.Listr is not a constructor

### ISSUE THREAD

**Issue by dhmacs** [Shopify/oxygenctl-action#34]
I'm testing Hydrogen and when I push the build phase breaks with this error:

<img width="848" alt="Screenshot 2022-07-07 at 23 04 58" src="https://user-images.githubusercontent.com/4640135/177871180-67b6b1a6-4c73-4f18-a5e4-2d8a73ca1148.png">

When I build the app locally  (`npm run build`) it works fine. 

Any idea about what might cause the build to succeed on localhost but not on CI?

**Comment by jgodson** [comment]
Thanks for the bug reports! Apologies, we hadn't been watching this repo for issues, but it looks like it was fixed at some point based on the code I currently see in the [Shopify CLI](https://github.com/Shopify/cli/blob/b88c2ebb986f2f020f48aec67f6291e5ad13be97/packages/cli-hydrogen/src/cli/services/build.ts#L47) repo, so I'm going to close this now.
