### ISSUE TITLE
oxygenctl bump is causing deployment to fail

### ISSUE THREAD

**Issue by webmarkyn** [Shopify/oxygenctl-action#68]
After commit 9952bd346c94006c5b5ace53ec9e654f3323facf deployment always fails with one of the following reasons:
- Failed to create build. Labels is invalid
- Failed to create deployment. Namespace must exist (if build has been successful)

Rollback to commit before oxygenctl bump to 4.4.0 solves the issue.

**Comment by webmarkyn** [comment]
I was wrong, using the previous version does not work, it just worked once for me, but after retry it failed again. I don't know what's the problem, but 5 days ago I could successfully deploy new storefront versions to Shopify and now it fails. Even if I retry to deploy storefront commit that was successfully deployed 7 days ago it would fail now with one of the errors mentioned avobe

**Comment by jgodson** [comment]
Sorry did not see this at the time, but I am guessing the problem has been resolved now?
