### ISSUE TITLE
Oxygen deployment failing with error: Cannot find package '@shopify/cli-kit'

### ISSUE THREAD

**Issue by adnanlazer** [Shopify/oxygenctl-action#89]
### Which package or tool is having this issue?

Oxygen

### What version of that package or tool are you using?

shopify/oxygenctl-action@v4

### What version of Remix are you using?

2.6.0

### Steps to Reproduce

Deploy to oxygen using github actions

### Expected Behavior

Successful deployment

### Actual Behavior

Failing with following error message:

<img width="1281" alt="image" src="https://github.com/Shopify/hydrogen/assets/88470780/edb81d54-6e5c-40eb-a53e-da12b594ecbb">

**Comment by jgodson** [comment]
Hi there! We recently updated the version of oxygen-cli we were using. We have reverted that change and this should be resolved now.

I am curious if by any chance you have turned off peer dependency installation similar to [this issue](https://github.com/Shopify/oxygenctl-action/issues/88#issuecomment-1943669790)?
